'use client'

import { useState } from 'react'
import { ChangingFontText } from '@/components/ChangingFontText'
import { FontSearch } from '@/components/FontSearch'
import { FontSimilar } from '@/components/FontSimilar'
import { 
  pretendard,
  notoSansKr,
  blackHanSans,
  jua,
  doHyeon,
  stylish,
  poorStory,
  nanumPenScript,
  gaegu,
  watermelon,
  bagelfatone,
  banggraeMelon,
  bmdohyeon,
  bmeuljiro10yearslater,
  bmeuljirooraeorae,
  bmhannaair,
  cafe24ClassicType,
  cafe24Ohsquare,
  cafe24OneprettyNight,
  cafe24SsurroundAir,
  chab,
  changwonDangamRound,
  chosunGu,
  climateCrisisKR2010,
  d2Coding,
  ddag,
  dnfforgedblade,
  dosGothic,
  dungGeunMo,
  efCucumbersalad,
  efJejudoldam,
  efMacho,
  elandNice,
  elandChoice,
  eliceDigitalCoding,
  esamanru,
  establishRetrosans,
  galmuri11,
  giant,
  gmarketSansTTF,
  goormSansRegular,
  gumiIndustry,
  hahmlet,
  hakgyoansimAllimjang,
  hakgyoansimDunggeunmiso,
  hakgyoansimPuzzle,
  hancomMalangMalang,
  heirOfLight,
  hssBomBaram,
  hssSantokki,
  hssSantokki2,
  intelOneMono,
  jalnan2,
  koPubBatang,
  lineSeedKR,
  moveSans,
  mungyeongGamhong,
  nexonLv1Gothic,
  nanumGothic,
  nanumSquare,
  nanumSquareRound,
  noonnuBasicGothic,
  notoSansKR,
  okGung,
  okmanFont,
  oneMobileTitle,
  orbit,
  paperlogy,
  puradakGentleGothic,
  pyeongChangPeace,
  roehoeChan,
  rokafSlabSerif,
  riaSans,
  sdSamliphopangche,
  sdSamliphopangcheOutline,
  sebangGothic,
  sfSsaraknun,
  smuSnowflake,
  sogangUniversity,
  sam3KRFont,
  tdtdTadakTadak,
  tenada,
  theJamsil,
  tmoneyRoundWind,
  vitroCore,
  vitroInspire,
  vitroPride,
  wantedSans,
  yOnepick,
  yUniverse,
  ycomputer,
  yeongdo,
  twaySky,
  binpol2020,
  miwon,
  ongleafConcon,
  gangwonEduAll,
  gangwonEduPower,
  gyeonggiCheonnyeonBatang,
  mabinogiClassic,
  mangoDdobak,
  maplestory,
  moneygraphy,
} from '@/lib/fonts'

const fontMap = {
  '프리텐다드': pretendard,
  '116수박화체': watermelon,
  '베이글팻': bagelfatone,
  '빙그레메로나체': banggraeMelon,
  '도현체': bmdohyeon,
  '을지로10년후체': bmeuljiro10yearslater,
  '을지로오래오래체': bmeuljirooraeorae,
  '한나체Air': bmhannaair,
  '카페24클래식타입': cafe24ClassicType,
  '카페24아네모네': cafe24Ohsquare,
  '카페24고운밤': cafe24OneprettyNight,
  '카페24써라운드에어': cafe24SsurroundAir,
  '리아체': chab,
  '창원단감아삭체': changwonDangamRound,
  '조선굴림체': chosunGu,
  '기후위기-한글': climateCrisisKR2010,
  'D2Coding': d2Coding,
  '롯데리아딱붙어체': ddag,
  '던파연단된칼날': dnfforgedblade,
  '도스고딕': dosGothic,
  '둥근모꼴+Fixedsys': dungGeunMo,
  '오이냉체': efCucumbersalad,
  '제주돌담체': efJejudoldam,
  '마초체': efMacho,
  '이랜드나이스체': elandNice,
  '이랜드초이스체': elandChoice,
  '엘리스디지털코딩체': eliceDigitalCoding,
  '이사만루': esamanru,
  '설립체유건욱': establishRetrosans,
  '갈무리11': galmuri11,
  '자이언츠체': giant,
  'G마켓산스': gmarketSansTTF,
  '구름산스': goormSansRegular,
  '구미첨단산업체': gumiIndustry,
  '함렛': hahmlet,
  '학교안심알림장': hakgyoansimAllimjang,
  '학교안심둥근미소': hakgyoansimDunggeunmiso,
  '학교안심퍼즐': hakgyoansimPuzzle,
  '한컴말랑말랑': hancomMalangMalang,
  '빛의계승자체': heirOfLight,
  'HS봄바람체2.0': hssBomBaram,
  'HS산토끼체': hssSantokki,
  'HS산토끼체2.0': hssSantokki2,
  'IntelOneMono': intelOneMono,
  '여기어때잘난체2': jalnan2,
  'KoPub바탕': koPubBatang,
  'LINESeed': lineSeedKR,
  '마비옛체': mabinogiClassic,
  '망고보드또박체': mangoDdobak,
  '넥슨메이플스토리': maplestory,
  '머니그라피-픽셀': moneygraphy,
  'MoveSans': moveSans,
  '문경감홍사과체': mungyeongGamhong,
  '넥슨Lv.1고딕': nexonLv1Gothic,
  '나눔고딕': nanumGothic,
  '나눔스퀘어': nanumSquare,
  '나눔스퀘어라운드': nanumSquareRound,
  '눈누기초고딕': noonnuBasicGothic,
  '본고딕': notoSansKR,
  '읏맨-궁서체': okGung,
  '읏맨-엉뚱체': okmanFont,
  '원스토어모바일고딕제목체': oneMobileTitle,
  '오르빗': orbit,
  '페이퍼로지': paperlogy,
  '푸라닭젠틀고딕': puradakGentleGothic,
  '평창체': pyeongChangPeace,
  '노회찬체': roehoeChan,
  '바른공군체': rokafSlabSerif,
  '리아체': riaSans,
  '삼립호빵체': sdSamliphopangche,
  '삼립호빵체outline': sdSamliphopangcheOutline,
  '세방고딕체': sebangGothic,
  '싸락눈체': sfSsaraknun,
  '숙명눈꽃체': smuSnowflake,
  '서강체': sogangUniversity,
  '삼국지3글꼴': sam3KRFont,
  '타닥타닥체': tdtdTadakTadak,
  '태나다체': tenada,
  '더잠실체': theJamsil,
  '티머니둥근바람': tmoneyRoundWind,
  '비트로코어체': vitroCore,
  '비트로인스파이어체': vitroInspire,
  '비트로프라이드체': vitroPride,
  'WantedSans': wantedSans,
  'Y최애체': yOnepick,
  'Y유니버스체': yUniverse,
  'Y콤퓨타체': ycomputer,
  '영도체': yeongdo,
  '티웨이날다체': twaySky,
  '빈폴2020': binpol2020,
  '미원체': miwon,
  '온글잎콘콘체': ongleafConcon,
  '강원교육모두': gangwonEduAll,
  '강원교육튼튼': gangwonEduPower,
  '경기천년바탕': gyeonggiCheonnyeonBatang
}

export default function Home() {
  const [searchQuery, setSearchQuery] = useState('')
  const fontList = Object.keys(fontMap)

  return (
    <main className="min-h-screen max-w-4xl mx-auto px-4 py-8">
      <section className="flex flex-col items-center justify-center text-center">
        <h1 className="text-5xl md:text-5xl font-bold mb-6">
          <ChangingFontText />
        </h1>
        <p className="text-lg text-gray-600 mb-8 max-w-2xl">
          수천 개의 폰트 중에서 가장 비슷한 폰트를 찾아드립니다
        </p>
        <FontSearch onSearch={setSearchQuery} fontList={fontList} />
        <FontSimilar searchQuery={searchQuery} fontMap={fontMap} />
      </section>
    </main>
  )
}
